#!/usr/bin/env python3
"""Nexus Loop cold-run entrypoint.

    python3 run.py --kit kit --team nexus-loop --out out/loop-report.json
    python3 run.py --kit kit --replay-url http://127.0.0.1:8719 --serve

Unattended: load the kit, build the session table, answer the eleven asks,
detect the three fault classes, dismiss the three lookalikes, freeze a golden
set, propose decision-shaped fixes, optionally verify one of them against the
replay endpoint, validate, write, and score when ground truth is present.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time

ROOT = os.path.dirname(os.path.abspath(__file__))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from nexus_loop.asks import build as build_asks
from nexus_loop.coverage import Coverage
from nexus_loop.decoys import detect_all as detect_decoys
from nexus_loop.detect import detect_all as detect_faults
from nexus_loop.features import Corpus
from nexus_loop.io import Kit, KitError, write_json_atomic
from nexus_loop.report import assemble, attach_verifications, replay_queue, strip_internal
from nexus_loop.replay import health as replay_health
from nexus_loop.replay import run_all as run_replays
from nexus_loop.standards import freeze_golden_sets
from nexus_loop.validate import extra_checks, load_schema, validate


SCHEMA_CANDIDATES = (
    os.path.join(ROOT, "tools", "nexus-loop-kit", "schema", "loop-report.schema.json"),
    os.path.join(ROOT, "schema", "loop-report.schema.json"),
)
SCORE_CANDIDATES = (
    os.path.join(ROOT, "tools", "nexus-loop-kit", "score.py"),
    os.path.join(ROOT, "score.py"),
)


def _first_existing(paths) -> str:
    for p in paths:
        if os.path.exists(p):
            return p
    return paths[0]


def system_notes(corpus: Corpus, cov: Coverage, replay_notes: list, n_reg: int, n_decoy: int) -> str:
    tool_cov = {t: cov.value("tool_call", t) for t in corpus.tenants}
    lines = [
        "REAL: session-grain feature table from sessions.jsonl.gz + agent_steps.jsonl.gz; "
        "coverage computed per tenant from which agent_kinds emit each step type in THIS "
        "corpus (tool_call coverage %s); 11 asks answered with a metric or a structured gap; "
        "three detector-specific analyses (tool contract / KB gap with same-tenant peers / "
        "prompt efficiency with sibling-agent control); three explicit decoy dismissals; "
        "A11 refused with required event failover {from_target,to_target,reason,recovered} "
        "owner conversation-runtime; cost is the sum of recorded cost_usd or null; "
        "cardinality refusal cites the catalog's fixed budget of 200 on "
        "session.custom_dims.customer_ref; golden-set IDs frozen to out/golden_set.json "
        "before any prescription; decision screen renders this report and writes approval "
        "back into it."
        % ", ".join("%s=%.3f" % kv for kv in tool_cov.items()),
        "STUBBED: no LLM is called anywhere. A09 (why a user abandoned) is a REQUIRES_NEW_JUDGE "
        "gap rather than a trained frustration classifier. Quality calibration uses the kit's "
        "human rubric labels against the corpus's own judge, not a judge we trained.",
        "SIMULATED: the replay endpoint (replay/serve.py) is a hypothesis verifier with a seeded "
        "effect model. Its 'before' is not this system's corpus measurement. We send at most a "
        "few high-confidence runs on the exact detected cohort; no_effect is recorded honestly. "
        + ("Replay this run: " + "; ".join(replay_notes) if replay_notes else "Replay not attempted."),
        "BREAKS AT 100x: the session map is in-memory (~80k sessions, ~900k steps is comfortable; "
        "tens of millions of sessions would need an on-disk grain and a streaming window scan). "
        "The decision screen writes the report file atomically — that is not a multi-user store. "
        "Detector thresholds are relative/statistical, not practice literals, but a sealed corpus "
        "with a different empty-success base rate still has to clear the same lift/z bars.",
        "This file is generated by run.py from the kit corpus; no hand-edited or reference report is read or copied.",
        "Findings this run: %d regressions, %d explicit non-regressions." % (n_reg, n_decoy),
    ]
    return "\n\n".join(lines)


def write_report(path: str, report: dict) -> None:
    write_json_atomic(path, strip_internal(report), allow_nan=False)


def load_prior_approvals(path: str) -> dict:
    """Approvals from an earlier report at the same path, keyed by
    (prescription id, diagnosis id, target) so a re-run keeps human verdicts."""
    if not os.path.exists(path):
        return {}
    try:
        with open(path, encoding="utf-8") as fh:
            prior = json.load(fh)
    except (OSError, ValueError):
        return {}
    out = {}
    for p in prior.get("prescriptions") or []:
        a = p.get("approval")
        if a:
            out[(p.get("id"), p.get("diagnosis_id"), p.get("target"))] = a
    return out


def maybe_score(report_path: str, kit_root: str) -> int:
    gt = None
    for cand in (os.path.join(kit_root, "ground_truth", "ground_truth.json"),
                 os.path.join(kit_root, "ground_truth_SEALED", "ground_truth.json")):
        if os.path.exists(cand):
            gt = cand
            break
    if not gt:
        print("score: no ground truth next to the kit; skipped")
        return 0
    score_py = _first_existing(SCORE_CANDIDATES)
    if not os.path.exists(score_py):
        print("score: score.py not found; skipped")
        return 0
    print("\n--- score.py ---")
    return subprocess.call([sys.executable, score_py, "--report", report_path,
                            "--ground-truth", gt])


def main(argv=None) -> int:
    try:
        sys.stdout.reconfigure(line_buffering=True)
    except Exception:
        pass
    ap = argparse.ArgumentParser(description="Nexus Loop cold run")
    ap.add_argument("--kit", default=os.path.join(ROOT, "kit"))
    ap.add_argument("--corpus-dir", default=None,
                    help="override corpus directory (e.g. kit/corpus_sample)")
    ap.add_argument("--team", default="nexus-loop")
    ap.add_argument("--out", default=os.path.join(ROOT, "out", "loop-report.json"))
    ap.add_argument("--replay-url", default="http://127.0.0.1:8719")
    ap.add_argument("--no-replay", action="store_true")
    ap.add_argument("--replay-max", type=int, default=1,
                    help="max genuine replay runs (default 1; never null/wrong probes)")
    ap.add_argument("--schema", default=_first_existing(SCHEMA_CANDIDATES))
    ap.add_argument("--no-score", action="store_true")
    ap.add_argument("--serve", action="store_true", help="start the decision screen after writing")
    ap.add_argument("--port", type=int, default=8765)
    a = ap.parse_args(argv)

    t0 = time.time()
    print("kit        %s" % a.kit)
    print("corpus     %s" % (a.corpus_dir or os.path.join(a.kit, "corpus")))
    print("team       %s" % a.team)
    print("out        %s" % a.out)

    try:
        kit = Kit(a.kit, corpus_dir=a.corpus_dir)
    except KitError as e:
        print("error: %s" % e, file=sys.stderr)
        return 2

    print("loading session table …")
    corpus = Corpus(kit).load()
    print("  %d sessions, %d days, tenants %s, %d config changes, %d orphan steps"
          % (len(corpus.sessions), corpus.days, ",".join(corpus.tenants),
             len(corpus.changes), corpus.orphan_steps))
    cov = Coverage(corpus)
    print("  tool_call coverage: %s" %
          ", ".join("%s=%.3f" % (t, cov.value("tool_call", t)) for t in corpus.tenants))

    print("detectors …")
    regressions = detect_faults(corpus, cov)
    decoys = detect_decoys(corpus, regressions)
    print("  %d regression(s): %s" % (
        len(regressions),
        ", ".join("%s/%s %s" % (o["kind"], o["tenant"], o["cohort"]) for o in regressions) or "none"))
    print("  %d decoy(s): %s" % (
        len(decoys),
        ", ".join("%s/%s" % (o["kind"], o["tenant"]) for o in decoys) or "none"))

    print("asks …")
    metrics, gaps, extras = build_asks(corpus, cov, kit.catalog, regressions, decoys)
    print("  %d metrics, %d gaps" % (len(metrics), len(gaps)))

    golden_path = os.path.join(os.path.dirname(os.path.abspath(a.out)), "golden_set.json")
    print("freezing golden sets → %s" % golden_path)
    freeze_golden_sets(regressions, cov, golden_path, kit.corpus_variant)

    notes_so_far: list = []
    report = assemble(
        a.team, corpus, cov, metrics, gaps, regressions, decoys,
        verifications=[], extras=extras,
        system_notes=system_notes(corpus, cov, notes_so_far, len(regressions), len(decoys)),
        prior_approvals=load_prior_approvals(a.out),
    )

    replay_notes: list = []
    if a.no_replay:
        replay_notes.append("replay skipped (--no-replay)")
    else:
        print("replay %s …" % a.replay_url)
        queue = replay_queue(report)
        # stash tenant on each prescription for the client
        tenants = {p["id"]: tenant for p, tenant in queue}
        for p in report.get("prescriptions") or []:
            if p["id"] in tenants:
                p["tenant"] = tenants[p["id"]]  # run_all reads tenants map, not this
        vers, replay_notes = run_replays(
            a.replay_url, a.team,
            [p for p, _ in queue],
            tenants,
            max_runs=max(0, a.replay_max),
            audit_path=os.path.join(os.path.dirname(os.path.abspath(a.out)), "replay.log"),
        )
        attach_verifications(report, vers)
        for n in replay_notes:
            print("  %s" % n)

    report["system_notes"] = system_notes(corpus, cov, replay_notes, len(regressions), len(decoys))
    preserved = [p for p in report.get("prescriptions") or [] if p.get("approval")]
    if preserved:
        report["system_notes"] += (
            "\n\nPRESERVED: %d recorded human verdict(s) carried forward from the prior report at this "
            "path, matched by prescription id, diagnosis and target; the pipeline did not overwrite them."
            % len(preserved))

    schema = load_schema(a.schema)
    public = strip_internal(report)
    problems = validate(public, schema) + extra_checks(public)
    if problems:
        print("VALIDATION FAILED (%d):" % len(problems), file=sys.stderr)
        for p in problems[:40]:
            print("  %s" % p, file=sys.stderr)
        # still write so we can inspect
        write_report(a.out, report)
        return 3

    write_report(a.out, report)
    print("wrote      %s  (%.1fs)" % (a.out, time.time() - t0))
    print("  findings %d  diagnoses %d  prescriptions %d  verifications %d  metrics %d  gaps %d"
          % (len(public["findings"]), len(public["diagnoses"]), len(public.get("prescriptions") or []),
             len(public.get("verifications") or []), len(public["metrics"]), len(public["gaps"])))

    rc = 0
    if not a.no_score:
        rc = maybe_score(a.out, a.kit)

    if a.serve:
        from nexus_loop.app import serve
        print("decision screen http://127.0.0.1:%d  (Ctrl-C to stop)" % a.port)
        serve(a.out, a.schema, a.port)
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
