#!/usr/bin/env python3
"""General testbed for Nexus Loop candidate solutions.

It does not assume any particular implementation. A candidate is described by a
command template and tested, unattended, against several held-out (sealed)
corpora generated by the kit itself. For each corpus it:

  1. starts the kit's replay service and passes its URL to the candidate;
  2. runs the candidate cold (twice, to check determinism) with stdin closed;
  3. requires a schema-valid ``loop-report.json`` from one command;
  4. scores it with the organiser's own ``score.py`` against the held-out key;
  5. checks the faults, the decoys, stray findings, and the deliverable
     invariants the scorer does not enforce;
  6. scans the candidate source for practice literals (generality);
  7. exercises the decision screen and its write-back (if the candidate serves one).

A candidate passes only when every corpus yields: every fault found with the
right cohort and cause and no detection lag, every decoy not falsely flagged,
no strays, honesty = 12, schema-valid, determinism, no practice literals, a
working approval write-back, and a real replay verification when a replay URL
was provided.

Usage:
    python3 testbed/evaluate.py --candidates testbed/candidates.json
    python3 testbed/evaluate.py --candidate anupam-pr1 --quick
"""
from __future__ import annotations

import argparse
import glob
import importlib.util
import json
import os
import re
import shutil
import socket
import subprocess
import sys
import time
from typing import Dict, List, Optional, Tuple

HERE = os.path.dirname(os.path.abspath(__file__))


def _find_tools() -> str:
    """Locate tools/nexus-loop-kit whether the testbed lives at <repo>/testbed
    or <repo>/tools/testbed."""
    cands = [
        os.path.join(os.path.dirname(HERE), "nexus-loop-kit"),
        os.path.join(HERE, "nexus-loop-kit"),
        os.path.join(os.path.dirname(HERE), "tools", "nexus-loop-kit"),
        os.path.join(os.path.dirname(os.path.dirname(HERE)), "tools", "nexus-loop-kit"),
        os.path.join(HERE, "..", "yellow-ai", "tools", "nexus-loop-kit"),
    ]
    for c in cands:
        if os.path.exists(os.path.join(c, "score.py")):
            return os.path.abspath(c)
    return os.path.abspath(cands[0])


DEFAULT_TOOLS = _find_tools()
sys.path.insert(0, HERE)
import schema_check  # noqa: E402

DECOY_CAUSE = {"traffic_mix_shift": "traffic_mix", "load_event": "load",
               "judge_version_boundary": "judge_change"}


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #

def load_module(path: str, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def free_port() -> int:
    s = socket.socket()
    s.bind(("127.0.0.1", 0))
    port = s.getsockname()[1]
    s.close()
    return port


def sanitized_kit(kit: str, dest: str) -> str:
    """A copy of the kit for the candidate with the sealed answer keys removed.

    The candidate must not be able to read `ground_truth*`; a real copy (not
    symlinks) keeps the path self-contained, so `realpath` cannot walk back to
    the key either. The key is passed only to the scorer."""
    if os.path.isdir(dest):
        return dest
    shutil.copytree(kit, dest,
                    ignore=shutil.ignore_patterns("ground_truth", "ground_truth_SEALED"))
    return dest


def run(cmd: str, cwd: str, timeout: int, env=None) -> Tuple[int, str, float]:
    t0 = time.time()
    p = subprocess.run(cmd, shell=True, cwd=cwd, stdin=subprocess.DEVNULL,
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                       text=True, timeout=timeout, env=env)
    return p.returncode, p.stdout, time.time() - t0


def _terminate(proc) -> None:
    import signal
    try:
        pgid = os.getpgid(proc.pid)
    except Exception:
        pgid = None
    try:
        if pgid is not None and pgid != os.getpgid(0):
            os.killpg(pgid, signal.SIGTERM)
        else:
            proc.terminate()
    except Exception:
        try:
            proc.terminate()
        except Exception:
            pass
    try:
        proc.wait(timeout=5)
    except Exception:
        try:
            proc.kill()
        except Exception:
            pass


def wait_http(url: str, timeout: float = 20.0) -> bool:
    import urllib.request
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=1) as r:
                if r.status == 200:
                    return True
        except Exception:
            time.sleep(0.3)
    return False


def post_json(url: str, payload: dict, timeout: float = 10.0) -> Tuple[int, str]:
    import urllib.request
    import urllib.error
    req = urllib.request.Request(url, data=json.dumps(payload).encode(),
                                 headers={"Content-Type": "application/json"}, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return r.status, r.read().decode()
    except urllib.error.HTTPError as e:  # type: ignore[attr-defined]
        return e.code, e.read().decode()


def normalize(report: dict) -> dict:
    """Drop volatile fields so two runs can be compared for determinism."""
    def walk(o):
        if isinstance(o, dict):
            return {k: walk(v) for k, v in o.items()
                    if k not in ("generated_at", "at", "generated", "out", "team",
                                 "runs_used", "run_budget")}
        if isinstance(o, list):
            return [walk(x) for x in o]
        return o
    return walk(report)


# --------------------------------------------------------------------------- #
# objective checks (faults / decoys / strays) using the organiser's matcher
# --------------------------------------------------------------------------- #

def objective(report: dict, gt: dict, scoremod) -> Dict:
    faults = gt["faults"]
    decoys = gt["decoys"]
    findings = report.get("findings", [])
    regs = [f for f in findings if f.get("is_regression")]
    diags = {d["finding_id"]: d for d in report.get("diagnoses", [])}
    res = {"faults": {}, "decoys": {}, "strays": []}
    per = 20.0 / float(len(faults))

    for flt in faults:
        hits = [f for f in regs if scoremod.match_fault(f, [flt])]
        if not hits:
            res["faults"][flt["id"]] = {"found": False, "points": 0.0,
                                        "max": round(per, 2), "lost": round(per, 2)}
            continue
        best = min(hits, key=lambda f: abs(f["window"].get("from_day", 0) - flt["onset_day"]))
        lag = max(0, best["window"].get("from_day", 0) - flt["onset_day"])
        d = diags.get(best["id"], {})
        cohort_ok = scoremod.cohort_matches(best.get("cohort") or {}, flt.get("cohort") or {})
        cause = d.get("cause_class")
        exp_cause = flt["cause_class"]
        cause_ok = cause == exp_cause
        ac = d.get("attributed_change") or {}
        exp_ch = flt.get("attributable_change") or {}
        attr_ok = bool(cause) and ac.get("kind") == exp_ch.get("kind") and isinstance(ac.get("day"), int) \
            and abs(ac["day"] - exp_ch.get("day", -99)) <= 2
        # mirror score.py's accuracy arithmetic (detection + localisation + diagnosis)
        det = 0.45 * max(0.35, 1.0 - (lag / float(scoremod.DETECT_GRACE)) * 0.65)
        loc = 0.20 if cohort_ok else 0.0
        dg = 0.35 if cause_ok else (0.18 if cause and exp_cause.split(".")[0] == cause.split(".")[0] else 0.0)
        if dg and attr_ok:
            dg = min(0.35, dg + 0.05)
        got = (det + loc + dg) * per
        res["faults"][flt["id"]] = {
            "found": True, "lag": lag, "cohort_ok": cohort_ok, "cause_ok": cause_ok,
            "cause": cause, "expected_cause": exp_cause, "attribution_ok": attr_ok,
            "candidate_finding": best["id"], "candidate_cohort": best.get("cohort"),
            "candidate_window": best.get("window"), "candidate_observed": best.get("observed"),
            "candidate_expected": best.get("expected"), "attributed_change": ac,
            "expected_change": exp_ch,
            "clean": cohort_ok and cause_ok and lag <= scoremod.DETECT_GRACE,
            "points": round(got, 2), "max": round(per, 2), "lost": round(per - got, 2),
        }

    per_dec = 0.28 * 15.0
    for dec in decoys:
        bad = [f for f in regs if scoremod.match_decoy(f, [dec])
               and not scoremod.match_fault(f, faults)]
        expect = DECOY_CAUSE[dec["kind"]]
        dismissed = [f for f in findings
                     if not f.get("is_regression")
                     and scoremod.match_decoy(f, [dec])
                     and f.get("not_a_regression_because")
                     and diags.get(f["id"], {}).get("cause_class") == expect]
        if bad:
            lost = per_dec
        elif dismissed:
            lost = 0.0
        else:
            lost = per_dec * 0.35
        res["decoys"][dec["id"]] = {
            "false_alarm": bool(bad), "false_alarm_ids": [f["id"] for f in bad],
            "explicitly_dismissed": bool(dismissed),
            "dismissal_finding": dismissed[0]["id"] if dismissed else None,
            "dismissal_cause": diags.get(dismissed[0]["id"], {}).get("cause_class") if dismissed else None,
            "expected_cause": expect,
            "clean": not bad and bool(dismissed),
            "points_lost": round(lost, 2), "max": round(per_dec, 2),
        }

    res["strays"] = [f["id"] for f in regs
                     if not scoremod.match_fault(f, faults) and not scoremod.match_decoy(f, decoys)]
    return res


def explain_kit(res: Dict) -> List[str]:
    """A point ledger: exactly where points were lost, and what the candidate said."""
    sc = res.get("score", {})
    sec = sc.get("sections", {})
    lines: List[str] = []
    total = sc.get("machine_score")
    if total is not None:
        lines.append("machine %s/55  (lost %.2f)" % (total, 55.0 - float(total)))
    for name in ("Diagnostic accuracy", "Specificity", "Loop completeness", "Honesty"):
        s = sec.get(name)
        if not s:
            continue
        lines.append("%-20s %5.2f/%-3d lost %.2f" % (name, s.get("score", 0), s.get("max", 0),
                                                     s.get("max", 0) - s.get("score", 0)))
        for n in s.get("notes", []):
            lines.append("    " + n)
    obj = res.get("objective") or {}
    for fid, f in obj.get("faults", {}).items():
        if f.get("lost", 0) <= 0.05:
            continue
        if not f.get("found"):
            lines.append("LOST %s %.2f — fault not detected" % (fid, f["lost"]))
            continue
        lines.append("LOST %s %.2f — candidate finding %s said cause=%s, expected %s; cohort_ok=%s lag=%d"
                     % (fid, f["lost"], f.get("candidate_finding"), f.get("cause"),
                        f.get("expected_cause"), f.get("cohort_ok"), f.get("lag", -1)))
        lines.append("        cohort=%s window=%s observed=%s expected=%s attributed=%s (wanted %s)"
                     % (f.get("candidate_cohort"), f.get("candidate_window"),
                        f.get("candidate_observed"), f.get("candidate_expected"),
                        f.get("attributed_change"), f.get("expected_change")))
    for did, d in obj.get("decoys", {}).items():
        if d.get("points_lost", 0) <= 0.05:
            continue
        if d.get("false_alarm"):
            lines.append("LOST %s %.2f — FALSE ALARM: reported %s as a regression"
                         % (did, d["points_lost"], d["false_alarm_ids"]))
        else:
            lines.append("LOST %s %.2f — never explicitly dismissed (no non-regression "
                         "finding with a linked %s diagnosis)"
                         % (did, d["points_lost"], d.get("expected_cause")))
    for sid in obj.get("strays", []):
        lines.append("STRAY %s — regression matching neither a fault nor a decoy" % sid)
    for sid in res.get("foreign_replay_ids", []) or []:
        lines.append("FOREIGN REPLAY ID %s — not issued by the replay service" % sid)
    for name in ("schema_problems", "invariants"):
        for e in res.get(name) or []:
            lines.append("%s: %s" % ("SCHEMA" if name == "schema_problems" else "INVARIANT", e))
    rules = res.get("rules") or {}
    for e in rules.get("llm_deps", []):
        lines.append("RULE1 (audit): %s" % e)
    for e in rules.get("yardstick_write", []):
        lines.append("RULE2: %s" % e)
    return lines


# --------------------------------------------------------------------------- #
# deliverable invariants the scorer does not enforce
# --------------------------------------------------------------------------- #

def invariants(report: dict) -> List[str]:
    errs: List[str] = []
    for sec in ("metrics", "findings", "diagnoses", "gaps"):
        if not isinstance(report.get(sec), list):
            errs.append("required section %r missing or not a list" % sec)
    for key in ("team", "corpus"):
        if not report.get(key):
            errs.append("required field %r missing" % key)

    for m in report.get("metrics", []):
        if m.get("fidelity") not in ("measured", "judged", "derived"):
            errs.append("metric %s has bad fidelity %r" % (m.get("id"), m.get("fidelity")))
        cov = m.get("coverage") or {}
        if cov.get("value") is None or not cov.get("basis"):
            errs.append("metric %s lacks coverage value/basis" % m.get("id"))
        if m.get("fidelity") == "judged":
            cal = m.get("calibration") or {}
            if cal.get("agreement") is None or cal.get("n") is None:
                errs.append("judged metric %s lacks calibration" % m.get("id"))
            elif cal["agreement"] >= 0.995:
                errs.append("metric %s claims calibration %.3f (>=0.995)" % (m.get("id"), cal["agreement"]))

    gaps = {g.get("ask_id"): g for g in report.get("gaps", [])}
    a11 = gaps.get("A11")
    if not a11:
        errs.append("no A11 gap")
    else:
        if a11.get("verdict") != "NOT_MEASURABLE":
            errs.append("A11 verdict is %r, expected NOT_MEASURABLE" % a11.get("verdict"))
        ev = a11.get("required_event") or {}
        want = {"from_target", "to_target", "reason", "recovered"}
        if ev.get("name") != "failover" or ev.get("grain") != "step" or not want.issubset(set(ev.get("fields") or [])):
            errs.append("A11 required_event incomplete: %r" % ev)

    a04 = [m for m in report.get("metrics", []) if m.get("ask_id") == "A04"]
    if not a04:
        errs.append("A04 has no metric (required ask)")
    elif not any(m.get("fidelity") == "measured" for m in a04):
        errs.append("A04 has no measured metric (got %r)" % [m.get("fidelity") for m in a04])

    if "A09" in gaps:
        if gaps["A09"].get("verdict") != "REQUIRES_NEW_JUDGE":
            errs.append("A09 gap verdict is %r" % gaps["A09"].get("verdict"))
    else:
        a09 = [m for m in report.get("metrics", []) if m.get("ask_id") == "A09"]
        if not a09:
            errs.append("A09 neither gap nor metric")
        elif not any(m.get("fidelity") == "judged" for m in a09):
            errs.append("A09 has no judged metric")

    # cardinality refusal: a customer_ref breakdown must be accompanied by a refusal gap
    if not any(g.get("verdict") == "CARDINALITY_REFUSED" for g in report.get("gaps", [])):
        errs.append("no CARDINALITY_REFUSED gap for custom_dims.customer_ref (budget 200)")
    return errs


def replay_ok(report: dict) -> Dict:
    vers = report.get("verifications") or []
    real = [v for v in vers if str(v.get("replay_run_id", "")).startswith("rp_")]
    improved = [v for v in real if v.get("verdict") == "improved"]
    return {"count": len(real), "improved": len(improved),
            "ok": bool(real) and bool(improved)}


# --------------------------------------------------------------------------- #
# practice-literal scan
# --------------------------------------------------------------------------- #

def literals_from_kit(kit: str) -> List[str]:
    cat = json.load(open(os.path.join(kit, "catalog.json")))
    names = set()
    for tkey, t in cat.get("tenants", {}).items():
        names.add(tkey)
        names.update(t.get("agents", []))
        names.update(t.get("tools", []))
    for tkey, intents in cat.get("milestones", {}).items():
        names.update(intents.keys())
    for gt_name in ("ground_truth_SEALED", "ground_truth"):
        gt_path = os.path.join(kit, gt_name, "ground_truth.json")
        if os.path.exists(gt_path):
            for flt in json.load(open(gt_path)).get("faults", []):
                names.update(str(v) for v in (flt.get("cohort") or {}).values())
            break
    return sorted(n for n in names if len(n) >= 4)


def literal_scan(workdir: str, globs: List[str], allow: List[str], literals: List[str]) -> List[Tuple[str, str]]:
    files: List[str] = []
    for g in globs:
        files.extend(glob.glob(os.path.join(workdir, g), recursive=True))
    allowset = set()
    for g in allow:
        allowset.update(os.path.abspath(p) for p in glob.glob(os.path.join(workdir, g), recursive=True))
    hits: List[Tuple[str, str]] = []
    for path in sorted(set(files)):
        if os.path.abspath(path) in allowset or not os.path.isfile(path):
            continue
        if os.path.getsize(path) > 2_000_000:
            continue
        try:
            text = open(path, encoding="utf-8", errors="ignore").read()
        except OSError:
            continue
        for lit in literals:
            if lit in text:
                hits.append((os.path.relpath(path, workdir), lit))
    return hits


# --------------------------------------------------------------------------- #
# rule checks (Rule 1: no LLM for logged facts; Rule 2: yardstick frozen)
# --------------------------------------------------------------------------- #

LLM_MARKERS = [
    "import openai", "from openai", "import anthropic", "from anthropic",
    "google.generativeai", "google.genai", "import cohere", "from cohere",
    "mistralai", "litellm", "import ollama", "from ollama",
    "transformers", "sentence_transformers", "api.openai.com", "api.anthropic.com",
    "generativelanguage.googleapis.com",
]
PROTECTED = ["catalog.json", "ground_truth", "loop-report.schema", "score.py"]


def _source_texts(workdir: str, globs: List[str], allow: List[str]):
    files: List[str] = []
    for g in globs:
        files.extend(glob.glob(os.path.join(workdir, g), recursive=True))
    allowset = set()
    for g in allow:
        allowset.update(os.path.abspath(p) for p in glob.glob(os.path.join(workdir, g), recursive=True))
    for path in sorted(set(files)):
        if os.path.abspath(path) in allowset or not os.path.isfile(path):
            continue
        if os.path.getsize(path) > 2_000_000:
            continue
        try:
            yield os.path.relpath(path, workdir), open(path, encoding="utf-8", errors="ignore").read()
        except OSError:
            continue


def rule_scan(workdir: str, globs: List[str], allow: List[str]) -> Dict:
    """Static, heuristic checks that are cheap and reviewable.

    - llm_deps: an LLM/embedding SDK is referenced. Rule 1 allows a model for
      meaning only; a human must confirm it is not used for logged facts.
    - yardstick_write: a path tries to write catalog/ground-truth/schema/score,
      which would be a Rule 2 violation (moving the yardstick).
    """
    out = {"llm_deps": [], "yardstick_write": []}
    for rel, text in _source_texts(workdir, globs, allow):
        low = text.lower()
        for marker in LLM_MARKERS:
            if marker.lower() in low:
                out["llm_deps"].append("%s: %s" % (rel, marker))
        for i, line in enumerate(text.splitlines(), 1):
            l = line.lower()
            if any(p.lower() in l for p in PROTECTED) and re.search(r"open\([^)]*['\"][wa]", l):
                out["yardstick_write"].append("%s:%d: %s" % (rel, i, line.strip()[:100]))
    return out


def fetch_json(url: str, timeout: float = 5.0):
    import urllib.request
    try:
        with urllib.request.urlopen(url, timeout=timeout) as r:
            return json.loads(r.read().decode())
    except Exception:
        return None


# --------------------------------------------------------------------------- #
# test one candidate on one kit
# --------------------------------------------------------------------------- #

def test_on_kit(cand: dict, kit: str, tools: str, args) -> Dict:
    name = cand["name"]
    workdir = cand.get("workdir", ".")
    outdir = os.path.join(args.out_root, name, os.path.basename(kit))
    os.makedirs(outdir, exist_ok=True)
    result: Dict = {"kit": os.path.basename(kit), "runs": [], "errors": [], "skipped": []}
    # the candidate never sees the sealed answer key
    run_kit = sanitized_kit(kit, os.path.join(outdir, "candidate-kit"))

    replay_url = ""
    replay_proc = None
    if cand.get("replay", True) and not args.no_replay:
        port = free_port()
        replay_url = "http://127.0.0.1:%d" % port
        replay_proc = subprocess.Popen(
            [sys.executable, os.path.join(tools, "replay", "serve.py"),
             "--kit", kit, "--port", str(port)],
            stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            start_new_session=True)
        if not wait_http(replay_url + "/health"):
            result["errors"].append("replay server did not start")
            replay_url = ""

    if not (cand.get("replay", True) and not args.no_replay):
        result["skipped"].append("replay (%s)" % ("--no-replay" if args.no_replay else "candidate replay=false"))
    elif not replay_url:
        result["skipped"].append("replay (server unavailable)")
    if args.quick:
        result["skipped"].append("determinism (--quick)")
    if not cand.get("serve"):
        result["skipped"].append("screen (candidate has no serve command)")
    elif args.no_screen:
        result["skipped"].append("screen (--no-screen)")

    try:
        reports = []
        n_runs = 1 if args.quick else 2
        for i in range(n_runs):
            sub = os.path.join(outdir, "run%d" % (i + 1))
            os.makedirs(sub, exist_ok=True)
            out = os.path.join(sub, "loop-report.json")
            cmd = cand["run"].format(kit=run_kit, team="%s-%s" % (name, os.path.basename(kit)),
                                     out=out, outdir=sub, replay_url=replay_url,
                                     port=free_port())
            try:
                rc, log, secs = run(cmd, workdir, args.timeout, env=os.environ.copy())
            except subprocess.TimeoutExpired:
                result["runs"].append({"rc": -9, "seconds": args.timeout, "report": False})
                result["errors"].append("run %d timed out after %ds" % (i + 1, args.timeout))
                return result
            result["runs"].append({"rc": rc, "seconds": round(secs, 1),
                                   "report": os.path.exists(out)})
            if rc != 0 or not os.path.exists(out):
                result["errors"].append("run %d failed rc=%d (%.1fs)\n%s"
                                        % (i + 1, rc, secs, log[-1500:]))
                return result
            reports.append(json.load(open(out)))
        report = reports[0]
        result["report_path"] = os.path.join(outdir, "run1", "loop-report.json")

        # replay provenance: every reported run id must have been issued by the
        # service during this candidate's run, and the reported verdict/before/
        # after must match what the service actually logged (no fabricated evidence)
        logged: Dict[str, dict] = {}
        if replay_url:
            log = fetch_json(replay_url + "/log")
            if log:
                logged = {r.get("run_id"): r for r in log.get("runs", [])}
        result["replay_log_ids"] = len(logged)
        foreign, mismatch = [], []
        pids = {p.get("id") for p in (report.get("prescriptions") or [])}
        for v in (report.get("verifications") or []):
            rid = str(v.get("replay_run_id", ""))
            if not rid.startswith("rp_"):
                continue
            if rid not in logged:
                foreign.append(rid)
                continue
            row = logged[rid]
            for fld in ("verdict", "before", "after"):
                rv, lv = v.get(fld), row.get(fld)
                if rv is None or lv is None:
                    continue
                if isinstance(rv, (int, float)) and isinstance(lv, (int, float)):
                    if abs(float(rv) - float(lv)) > 1e-6:
                        mismatch.append("%s.%s reported=%s logged=%s" % (rid, fld, rv, lv))
                elif rv != lv:
                    mismatch.append("%s.%s reported=%r logged=%r" % (rid, fld, rv, lv))
            if v.get("prescription_id") not in pids:
                mismatch.append("%s.prescription_id %r is not a prescription" % (rid, v.get("prescription_id")))
        result["foreign_replay_ids"] = foreign
        result["replay_mismatches"] = mismatch

        # schema + score
        schema = schema_check.load(os.path.join(tools, "schema", "loop-report.schema.json"))
        result["schema_problems"] = schema_check.problems(report, schema)
        result["schema_backend"] = schema_check.BACKEND
        gt = os.path.join(kit, "ground_truth_SEALED", "ground_truth.json")
        rc, out, _ = run("%s %s --report %s --ground-truth %s --json" % (
            sys.executable, os.path.join(tools, "score.py"),
            os.path.join(outdir, "run1", "loop-report.json"), gt), workdir, args.timeout)
        result["score"] = json.loads(out) if rc == 0 else {"error": out[-800:]}

        scoremod = load_module(os.path.join(tools, "score.py"), "nl_score")
        result["objective"] = objective(report, json.load(open(gt)), scoremod)
        result["invariants"] = invariants(report)
        result["replay"] = replay_ok(report)
        result["determinism"] = (n_runs == 1) or (normalize(reports[0]) == normalize(reports[1]))
        if not result["determinism"]:
            result["errors"].append("two cold runs produced different reports")

        # screen
        if cand.get("serve") and not args.no_screen:
            result["screen"] = screen_test(cand, outdir, report, args)
    finally:
        if replay_proc:
            _terminate(replay_proc)
    return result


def screen_test(cand: dict, outdir: str, report: dict, args) -> Dict:
    report_path = os.path.join(outdir, "run1", "loop-report.json")
    port = free_port()
    cmd = cand["serve"].format(report=report_path, port=port, outdir=outdir)
    proc = subprocess.Popen(cmd, shell=True, cwd=cand.get("workdir", "."),
                            stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL,
                            stderr=subprocess.DEVNULL, start_new_session=True)
    base = "http://127.0.0.1:%d" % port
    res = {"started": False, "page": False, "write_back": False, "reason_required": False}
    try:
        if not wait_http(base + "/", timeout=15):
            return res
        res["started"] = True
        import urllib.request
        with urllib.request.urlopen(base + "/", timeout=5) as r:
            body = r.read().decode("utf-8", "ignore")
            res["page"] = r.status == 200 and "<html" in body.lower()
        pres = report.get("prescriptions") or []
        if pres:
            pid = pres[0]["id"]
            st, _ = post_json(base + "/decision",
                              {"prescription_id": pid, "verdict": "accepted",
                               "decided_by": "testbed", "reason": "testbed check"})
            updated = json.load(open(report_path))
            got = [p for p in updated.get("prescriptions", []) if p["id"] == pid]
            res["write_back"] = st == 200 and bool(got and (got[0].get("approval") or {}).get("verdict"))
            st2, _ = post_json(base + "/decision",
                               {"prescription_id": pid, "verdict": "rejected",
                                "decided_by": "testbed", "reason": ""})
            res["reason_required"] = 400 <= st2 < 500
    except Exception as e:  # noqa: BLE001
        res["error"] = str(e)
    finally:
        _terminate(proc)
    return res


# --------------------------------------------------------------------------- #
# verdict + main
# --------------------------------------------------------------------------- #

def verdict(res: Dict, require_replay: bool, strict_rules: bool = False,
            lenient_invariants: bool = False) -> Tuple[bool, List[str]]:
    reasons: List[str] = []
    if res.get("errors"):
        return False, res["errors"]
    if res.get("schema_problems"):
        reasons.append("schema: %d problem(s)" % len(res["schema_problems"]))
    for fid, f in res["objective"]["faults"].items():
        if not f.get("clean"):
            reasons.append("fault %s not clean (%s)" % (fid, f))
    for did, d in res["objective"]["decoys"].items():
        if d["false_alarm"]:
            reasons.append("false alarm on %s" % did)
        if not d["explicitly_dismissed"]:
            reasons.append("decoy %s not explicitly dismissed" % did)
    if res["objective"]["strays"]:
        reasons.append("stray findings %s" % res["objective"]["strays"])
    if res["score"].get("sections", {}).get("Honesty", {}).get("score") != 12.0:
        reasons.append("honesty < 12")
    if res.get("invariants") and not lenient_invariants:
        reasons.append("invariants: %s" % res["invariants"][:3])
    if not res.get("determinism", True):
        reasons.append("non-deterministic")
    if res.get("literals") and res["literals"].get("violations"):
        reasons.append("practice literals: %s" % res["literals"]["violations"][:3])
    rules = res.get("rules") or {}
    if rules.get("yardstick_write"):
        reasons.append("Rule 2: code writes to a protected yardstick path: %s"
                       % rules["yardstick_write"][:2])
    if strict_rules and rules.get("llm_deps"):
        reasons.append("Rule 1 audit: LLM dependency referenced: %s" % rules["llm_deps"][:3])
    if res.get("foreign_replay_ids"):
        reasons.append("replay evidence not issued by the service: %s" % res["foreign_replay_ids"])
    if res.get("replay_mismatches"):
        reasons.append("replay evidence does not match the service log: %s"
                       % res["replay_mismatches"][:3])
    if require_replay and not res.get("replay", {}).get("ok"):
        reasons.append("no improved replay verification")
    if res.get("screen") and res["screen"].get("started"):
        if not (res["screen"]["page"] and res["screen"]["write_back"] and res["screen"]["reason_required"]):
            reasons.append("screen checks failed: %s" % res["screen"])
    return (not reasons), reasons


def main() -> int:
    ap = argparse.ArgumentParser()
    default_cands = os.path.join(HERE, "candidates.json")
    if not os.path.exists(default_cands):
        default_cands = os.path.join(HERE, "candidates.example.json")
    ap.add_argument("--candidates", default=default_cands)
    ap.add_argument("--candidate", default=None, help="only run this candidate name")
    ap.add_argument("--tools", default=DEFAULT_TOOLS)
    ap.add_argument("--kits-dir", default=os.path.join(HERE, "kits"))
    ap.add_argument("--out-root", default="/tmp/nexus-testbed/out")
    ap.add_argument("--timeout", type=int, default=600)
    ap.add_argument("--quick", action="store_true", help="one run per kit (skip determinism)")
    ap.add_argument("--no-screen", action="store_true")
    ap.add_argument("--no-replay", action="store_true")
    ap.add_argument("--strict-rules", action="store_true",
                    help="fail on any LLM dependency reference (Rule 1 audit)")
    ap.add_argument("--lenient-invariants", action="store_true",
                    help="do not fail on the extra deliverable invariants (schema+score only)")
    ap.add_argument("--explain", action="store_true",
                    help="print a point ledger: exactly which points were lost and why")
    ap.add_argument("--json-out", default=None)
    ap.add_argument("--matrix-out", default=None, help="write a markdown pass/fail matrix")
    a = ap.parse_args()

    cands = json.load(open(a.candidates))
    if isinstance(cands, dict):
        cands = cands.get("candidates", [])
    if a.candidate:
        cands = [c for c in cands if c["name"] == a.candidate]

    kits = sorted(d for d in glob.glob(os.path.join(a.kits_dir, "*"))
                  if os.path.exists(os.path.join(d, "ground_truth_SEALED", "ground_truth.json")))
    if not kits:
        print("no sealed kits in %s — run testbed/make_corpora.py first" % a.kits_dir)
        return 2

    # a single literal universe across the practice kit and every corpus under
    # test, so practice names are still caught on moved/renamed corpora
    lit_universe = set()
    practice = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(a.tools))), "kit")
    for k in ([practice] if os.path.exists(os.path.join(practice, "catalog.json")) else []) + kits:
        try:
            lit_universe.update(literals_from_kit(k))
        except Exception:
            pass
    all_literals = sorted(lit_universe)

    all_out = {}
    overall_pass = True
    for cand in cands:
        print("\n" + "=" * 78)
        print("CANDIDATE %s   (%s)" % (cand["name"], cand.get("workdir", ".")))
        print("=" * 78)
        rules = rule_scan(cand.get("workdir", "."),
                          cand.get("source_globs", ["**/*.py"]),
                          cand.get("literal_allow_globs", []))
        if rules.get("llm_deps"):
            print("  note: LLM dependency referenced (Rule 1 audit): %s" % rules["llm_deps"][:3])
        if rules.get("yardstick_write"):
            print("  note: Rule 2 risk, writes to protected path: %s" % rules["yardstick_write"][:2])
        cand_out = []
        for kit in kits:
            res = test_on_kit(cand, kit, a.tools, a)
            # literals and rules are candidate-level; attach to each result
            lits = all_literals
            res["literals"] = {
                "checked": lits,
                "violations": literal_scan(cand.get("workdir", "."),
                                           cand.get("source_globs", ["**/*.py"]),
                                           cand.get("literal_allow_globs", []), lits),
            }
            res["rules"] = rules
            res["explain"] = explain_kit(res)
            ok, reasons = verdict(res,
                                  require_replay=bool(cand.get("replay", True)) and not a.no_replay,
                                  strict_rules=a.strict_rules,
                                  lenient_invariants=a.lenient_invariants)
            res["pass"] = ok
            res["reasons"] = reasons
            sc = res.get("score", {})
            print("  %-22s %s  machine=%.1f/55  faults=%s decoys=%s %s" % (
                res["kit"],
                "PASS" if ok else "FAIL",
                sc.get("machine_score", -1),
                "".join("/" if f.get("clean") else "x" for f in res["objective"]["faults"].values()) if res.get("objective") else "?",
                "".join("/" if d.get("clean") else "x" for d in res["objective"]["decoys"].values()) if res.get("objective") else "?",
                "" if ok else "| " + "; ".join(reasons)[:110]))
            if a.explain:
                for ln in res["explain"]:
                    print("        " + ln)
            cand_out.append(res)
            overall_pass = overall_pass and ok
        all_out[cand["name"]] = cand_out

    if a.json_out:
        json.dump(all_out, open(a.json_out, "w"), indent=2, default=str)
        print("\nwrote %s" % a.json_out)

    if a.matrix_out:
        write_matrix(a.matrix_out, all_out)
        print("wrote %s" % a.matrix_out)

    print("\nOVERALL: %s" % ("ALL CANDIDATES PASS" if overall_pass else "FAILURES PRESENT"))
    return 0 if overall_pass else 1


def write_matrix(path: str, all_out: Dict) -> None:
    kits = sorted({r["kit"] for rows in all_out.values() for r in rows})
    candidates = list(all_out.keys())
    lines = ["# Testbed matrix", "", "| corpus | " + " | ".join(candidates) + " |",
             "|---" * (len(candidates) + 1) + "|"]
    for kit in kits:
        cells = []
        for cand in candidates:
            row = next((r for r in all_out[cand] if r["kit"] == kit), None)
            if row is None:
                cells.append("n/a")
            else:
                mark = "PASS" if row.get("pass") else "FAIL"
                sc = row.get("score", {}).get("machine_score")
                cells.append("%s (%.1f)" % (mark, sc) if isinstance(sc, (int, float)) else mark)
        lines.append("| %s | %s |" % (kit, " | ".join(cells)))
    lines.append("")
    lines.append("Faults F1/F2/F3 and decoys D1/D2/D3 are marked per corpus in the JSON output.")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    raise SystemExit(main())
