from pathlib import Path
import json
import shutil

run = Path(__file__).resolve().parent
comp = run / 'composition'
audio = json.loads((comp / 'assets/music/audio-data.json').read_text())
(comp / 'assets/music/audio-data.js').write_text('window.NEXUS_AUDIO_DATA=' + json.dumps({**audio, 'frames': audio['frames'][:720]}) + ';')
gsap = comp / 'node_modules/gsap/dist/gsap.min.js'
if gsap.exists():
    shutil.copy2(gsap, comp / 'assets/vendor/gsap.min.js')

logo = '<svg class="logo" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M15.5 7A6.5 6.5 0 1 0 16.5 10"/><path d="M16.5 3.5V7H13"/><circle cx="10" cy="10" r="1.6" fill="currentColor" stroke="none"/></svg>'
css = '''
@font-face{font-family:Inter;src:url('assets/fonts/InterVariable.woff2') format('woff2');font-weight:100 900;font-style:normal}
@font-face{font-family:'JetBrains Mono';src:url('assets/fonts/JetBrainsMono-Variable.woff2') format('woff2');font-weight:100 800;font-style:normal}
*{box-sizing:border-box}html,body{margin:0;width:1920px;height:1080px;overflow:hidden;background:#F6F7F9;color:#111827;font-family:Inter,sans-serif}#root{width:100%;height:100%;position:relative;overflow:hidden;background:#F6F7F9}h1,h2,p{margin:0}svg{display:block}.clip{position:absolute;inset:0}.stage{position:absolute;inset:0;opacity:0}.title{font-weight:650;letter-spacing:-.055em;line-height:1.08;font-size:82px}.muted{color:#5A6472}.mono{font-family:'JetBrains Mono',monospace}.eyebrow{font-size:25px;font-weight:550;letter-spacing:.07em;text-transform:uppercase;color:#2457C5}.tag{display:inline-flex;align-items:center;font-size:25px;font-weight:550;border-radius:8px;padding:13px 18px;line-height:1.2;white-space:nowrap}.tag.blue{background:#EEF3FF;color:#2457C5}.tag.green{background:#ECFDF3;color:#15803D}.tag.red{background:#FEF3F2;color:#B42318}
.brand-header{position:absolute;left:88px;right:88px;top:47px;height:53px;display:flex;align-items:center;gap:14px;z-index:30}.brand-header .logo{width:38px;height:38px;color:#2457C5}.brand-header .name{font-size:30px;font-weight:650;letter-spacing:-.025em}.brand-header .descriptor{font-size:23px;color:#5A6472;margin-left:auto}.header-rule{position:absolute;left:88px;right:88px;top:126px;height:2px;background:#E4E7EC;z-index:29}.footer{position:absolute;bottom:45px;left:88px;right:88px;display:flex;justify-content:space-between;align-items:center;color:#5A6472;font-size:22px;z-index:30}.footer .step{font-family:'JetBrains Mono',monospace;font-size:20px;letter-spacing:.02em}.footer .trail{display:flex;gap:10px}.footer .trail i{width:49px;height:4px;border-radius:4px;background:#D6DDE8}.footer .trail i.active{background:#2457C5}
.backline{position:absolute;left:55%;top:180px;width:500px;height:680px;border-left:1px solid #DCE5F5;transform:rotate(18deg);opacity:.6}.canvas-dot{position:absolute;right:110px;top:161px;width:12px;height:12px;border:3px solid #2457C5;border-radius:50%}
#problem-text{position:absolute;left:90px;top:232px;width:975px}.problem-title{font-size:118px;letter-spacing:-.06em;font-weight:650;line-height:1.03;margin-top:30px}.problem-title .resolved{color:#2457C5;display:block;margin-top:5px}.problem-note{font-size:32px;line-height:1.45;margin-top:36px;max-width:730px}.signal-stack{position:absolute;right:118px;top:240px;width:595px}.signal{background:#FFFFFF;border:2px solid #E4E7EC;border-radius:20px;padding:37px 42px;box-shadow:0 18px 48px #182B4610;height:226px}.signal .row{display:flex;justify-content:space-between;align-items:center}.signal .label{font-size:27px;font-weight:500;color:#5A6472}.signal .value{font-size:64px;font-weight:620;letter-spacing:-.045em;margin-top:26px}.signal .check{color:#15803D;width:52px;height:52px}.signal.bad{margin-top:44px;border-color:#F2C4C0;background:#FEF3F2}.signal.bad .value{font-size:57px;color:#B42318}.signal-join{position:absolute;top:226px;left:73px;height:44px;border-left:3px dashed #98A2B3}
#cause-head{position:absolute;left:90px;top:216px;width:494px}.cause-title{font-size:77px;line-height:1.1;margin-top:25px}.cause-body{font-size:31px;line-height:1.4;margin-top:26px;width:432px}.trace{position:absolute;left:91px;top:590px;width:470px}.trace-item{display:flex;align-items:center;gap:19px;padding:18px 0;font-size:31px;font-weight:520}.trace-num{font-family:'JetBrains Mono',monospace;font-size:19px;color:#2457C5;width:38px;height:38px;border:2px solid #A8BFF0;border-radius:50%;display:flex;align-items:center;justify-content:center;flex:none}.trace-item small{display:block;font-size:24px;font-weight:400;color:#5A6472;margin-top:4px}.product-window{position:absolute;left:630px;top:221px;width:1204px;height:751px;border:2px solid #C5CFDF;border-radius:22px;background:white;overflow:hidden;box-shadow:0 30px 65px #18314E20}.product-window img{display:block;width:1200px;height:750px}.window-frame{position:absolute;inset:0;border:2px solid #2457C5;border-radius:20px;pointer-events:none;opacity:.14}.focus-bracket{position:absolute;left:923px;top:376px;width:541px;height:172px;border:3px solid #2457C5;border-radius:10px;pointer-events:none;opacity:0}
#action-title{position:absolute;left:90px;top:193px;width:1710px}.action-title{font-size:80px;margin-top:23px}.action-sub{font-size:29px;line-height:1.4;margin-top:20px;color:#5A6472}.action-grid{position:absolute;left:90px;right:90px;top:452px;display:grid;grid-template-columns:1fr 1.17fr 1fr;gap:30px}.product-card{height:464px;border:2px solid #E4E7EC;background:white;border-radius:20px;padding:32px;box-shadow:0 12px 30px #18314E0A}.product-card .kicker{font-size:24px;color:#2457C5;display:flex;align-items:center;gap:10px;font-weight:550}.product-card .kicker .num{font-family:'JetBrains Mono',monospace;color:#5A6472}.product-card h2{font-size:42px;line-height:1.17;letter-spacing:-.04em;font-weight:620;margin-top:30px}.product-card p{font-size:27px;line-height:1.45;color:#3F4654;margin-top:21px}.dismiss-row{display:flex;justify-content:space-between;align-items:center;font-size:25px;border-top:1px solid #E4E7EC;padding-top:18px;margin-top:18px}.dismiss-row span:last-child{color:#15803D;font-weight:550}.bound-fix{border-color:#A5BAE9;background:#EEF3FF}.code-pill{font-size:25px;font-family:'JetBrains Mono',monospace;border:1px solid #B7C9EF;border-radius:8px;background:white;padding:16px;line-height:1.5;margin-top:25px;color:#2457C5}.replay-stat{margin-top:27px;font-size:66px;font-weight:630;color:#15803D;letter-spacing:-.06em}.replay-stat span{font-size:29px;color:#5A6472;font-weight:400;letter-spacing:0}.replay-good{font-size:27px;line-height:1.45;margin-top:14px;color:#3F4654}.card-footer{font-size:22px;color:#5A6472;margin-top:20px}.card-footer.practice{margin-top:27px}.check-badge{font-size:26px;font-weight:550;color:#15803D;margin-top:24px}
#decision-text{position:absolute;left:90px;top:221px;width:760px}.decision-title{font-size:87px;line-height:1.07;margin-top:25px}.decision-body{font-size:32px;line-height:1.42;width:650px;margin-top:30px}.decision-tags{display:flex;gap:16px;flex-wrap:wrap;margin-top:38px;width:700px}.decision-caption{position:absolute;left:91px;bottom:174px;width:700px;font-size:27px;color:#5A6472;line-height:1.4}.decision-panel{position:absolute;left:1053px;top:202px;width:580px;height:760px;background:white;border:2px solid #C5CFDF;border-radius:20px;box-shadow:0 26px 60px #18314E18;overflow:hidden}.decision-state{position:absolute;inset:0;overflow:hidden;background:white}.decision-state.approved{opacity:0}.decision-shot{position:absolute;left:-1955px;top:-595px;width:2720px;height:1700px;max-width:none}.approved .decision-shot{top:-408px}.cursor{position:absolute;left:1480px;top:700px;width:38px;height:50px;z-index:10;opacity:0}.press-ring{position:absolute;left:1470px;top:680px;width:62px;height:62px;border:3px solid #2457C5;border-radius:50%;opacity:0}
#close-text{position:absolute;left:90px;top:218px;width:1260px}.close-brand{display:flex;gap:20px;align-items:center;font-size:59px;font-weight:620;letter-spacing:-.04em}.close-brand .logo{color:#2457C5;width:62px;height:62px}.close-title{font-size:109px;margin-top:53px;max-width:1240px}.close-sub{font-size:48px;font-weight:450;letter-spacing:-.025em;color:#3F4654;margin-top:30px}.close-product{position:absolute;right:103px;bottom:173px;width:659px;height:395px;overflow:hidden;border:2px solid #C5CFDF;border-radius:15px;box-shadow:0 17px 40px #18314E17;opacity:0}.close-product img{width:655px;height:auto;display:block}.close-rule{position:absolute;left:93px;bottom:214px;width:835px;height:5px;background:#2457C5;transform-origin:left center}.close-meta{position:absolute;left:90px;bottom:260px;font-size:25px;letter-spacing:.035em;color:#2457C5}
'''
body = '''
<div class="backline" data-layout-ignore></div><div class="canvas-dot" data-layout-ignore></div>
<div class="brand-header">LOGO<span class="name">Nexus Loop</span><span class="descriptor">Quality control for AI support agents</span></div><div class="header-rule" data-layout-ignore></div>
<section class="clip" data-start="0" data-duration="4.7" data-track-index="1" id="scene-problem"><div class="stage" id="problem-stage">
<div id="problem-text"><div class="eyebrow">The hidden failure</div><h1 class="problem-title">Success ≠<span class="resolved">resolved.</span></h1><p class="problem-note muted">A healthy response code can hide a broken customer experience.</p></div>
<div class="signal-stack"><div class="signal" id="status-signal"><div class="row"><span class="label">Tool status</span><svg class="check" viewBox="0 0 40 40" fill="none" stroke="currentColor" stroke-width="3"><circle cx="20" cy="20" r="16"/><path d="m12 20 6 6 12-13"/></svg></div><div class="value mono">HTTP 200</div></div><div class="signal-join" data-layout-ignore></div><div class="signal bad" id="outcome-signal"><span class="label">Customer outcome</span><div class="value">Unresolved</div></div></div></div></section>
<section class="clip" data-start="4.45" data-duration="4.95" data-track-index="2" id="scene-cause"><div class="stage" id="cause-stage">
<div id="cause-head"><div class="eyebrow">The evidence connects</div><h1 class="title cause-title">Find what broke.</h1><p class="cause-body muted">Trace the failing cohort to the change behind it.</p></div>
<div class="trace"><div class="trace-item" id="trace-logs"><span class="trace-num">01</span><div>Agent logs<small>What the agent received</small></div></div><div class="trace-item" id="trace-outcomes"><span class="trace-num">02</span><div>Customer outcomes<small>What actually happened</small></div></div><div class="trace-item" id="trace-change"><span class="trace-num">03</span><div>Configuration change<small>What changed, and when</small></div></div></div>
<div class="product-window" id="product-window"><img src="assets/ui/finding.png" alt="Actual Nexus Loop operator console displaying silent tool failure and resolution decline"><div class="window-frame" id="reactive-frame" data-layout-ignore></div></div><div class="focus-bracket" data-layout-ignore></div></div></section>
<section class="clip" data-start="9.14" data-duration="6.35" data-track-index="3" id="scene-action"><div class="stage" id="action-stage">
<div id="action-title"><div class="eyebrow">From diagnosis to action</div><h1 class="title action-title">Real faults. Clear next steps.</h1><p class="action-sub">The fix, its risk, and its evidence — in one decision surface.</p></div>
<div class="action-grid"><div class="product-card" id="noise-card"><div class="kicker"><span class="num">01</span> Filter the noise</div><h2>Three lookalikes dismissed.</h2><div class="dismiss-row"><span>Traffic mix</span><span>Dismissed</span></div><div class="dismiss-row"><span>Temporary load</span><span>Dismissed</span></div><div class="dismiss-row"><span>Judge boundary</span><span>Dismissed</span></div><div class="card-footer practice">Practice corpus · 3 real faults found</div></div>
<div class="product-card bound-fix" id="fix-card"><div class="kicker"><span class="num">02</span> Recommend a bounded fix</div><h2>Validate the required result fields.</h2><div class="code-pill">Empty HTTP 200 → existing fallback</div><p>Risk and no-ship conditions stay visible.</p><div class="card-footer">Source: silent tool contract finding</div></div>
<div class="product-card" id="replay-card"><div class="kicker"><span class="num">03</span> Verify before deciding</div><h2>Protect what already works.</h2><div class="replay-stat">30 / 30 <span>passed</span></div><div class="replay-good">Known-good conversations</div><div class="check-badge">✓ 0 regressions</div><div class="card-footer">Seeded simulated replay</div></div></div></div></section>
<section class="clip" data-start="15.23" data-duration="3.62" data-track-index="4" id="scene-decision"><div class="stage" id="decision-stage">
<div id="decision-text"><div class="eyebrow">The operator has the call</div><h1 class="title decision-title">One decision.<span style="display:block">Every claim explained.</span></h1><p class="decision-body muted">Review the evidence. Record a verdict and the reason behind it.</p><div class="decision-tags"><span class="tag green">Approve</span><span class="tag red">Reject</span><span class="tag blue">Defer</span></div></div><p class="decision-caption">The verdict becomes a reusable decision note.</p>
<div class="decision-panel" id="decision-panel"><div class="decision-state review" id="review-state"><img class="decision-shot" data-layout-ignore src="assets/ui/review.png" alt="Actual review controls with a fictional product-team reviewer and reason"></div><div class="decision-state approved" id="approved-state"><img class="decision-shot" data-layout-ignore src="assets/ui/approved.png" alt="Recorded approval and Copy decision note in the actual console"></div></div>
<svg class="cursor" id="decision-cursor" data-layout-ignore viewBox="0 0 30 40"><path d="M3 2v29l8-7 7 13 5-3-7-13 10-1z" fill="white" stroke="#111827" stroke-width="2.5"/></svg><div class="press-ring" id="press-ring" data-layout-ignore></div></div></section>
<section class="clip" data-start="18.61" data-duration="5.39" data-track-index="5" id="scene-close"><div class="stage" id="close-stage">
<div id="close-text"><div class="close-brand">LOGONexus Loop</div><h1 class="title close-title">Know what to change.</h1><p class="close-sub">Keep the decision human.</p></div><div class="close-meta">DETECT · DIAGNOSE · PRESCRIBE · VERIFY · DECIDE</div><div class="close-rule" data-layout-ignore></div><div class="close-product" id="close-product"><img src="assets/ui/approved.png" alt="Nexus Loop evidence and recorded decision"></div></div></section>
<div class="footer"><span class="step" id="step-label">01 / THE PROBLEM</span><div class="trail" data-layout-ignore><i id="bar1" class="active"></i><i id="bar2"></i><i id="bar3"></i><i id="bar4"></i><i id="bar5"></i></div><span>Evidence in. Decisions out.</span></div>
<audio id="narration" src="assets/voiceover.wav" data-start="0.25" data-duration="22.208" data-track-index="10" data-volume="1"></audio>
<audio id="music-bed" src="assets/music/bed.mp3" data-start="0" data-duration="24" data-track-index="11" data-volume="0.3" data-automation="{&quot;version&quot;:1,&quot;lanes&quot;:[{&quot;target&quot;:&quot;volume&quot;,&quot;points&quot;:[{&quot;t&quot;:0,&quot;v&quot;:0},{&quot;t&quot;:0.3,&quot;v&quot;:0.15},{&quot;t&quot;:22.5,&quot;v&quot;:0.15},{&quot;t&quot;:22.8,&quot;v&quot;:0.27},{&quot;t&quot;:24,&quot;v&quot;:0}]}]}"></audio>
<audio id="sfx-reveal" src="assets/sfx/drop_001.ogg" data-start="4.55" data-duration="0.5" data-track-index="12" data-volume="0.22"></audio>
<audio id="sfx-selection" src="assets/sfx/select_008.ogg" data-start="17.48" data-duration="0.4" data-track-index="13" data-volume="0.25"></audio>
'''.replace('LOGO', logo)
script = '''
window.__timelines=window.__timelines||{};
const tl=gsap.timeline({paused:true});
function stage(id,start,end){tl.fromTo(id,{opacity:0},{opacity:1,duration:.22,ease:'power1.out'},start);if(end<24)tl.to(id,{opacity:0,duration:.2,ease:'power1.in'},end-.2);}
stage('#problem-stage',0,4.7);stage('#cause-stage',4.45,9.4);stage('#action-stage',9.14,15.49);stage('#decision-stage',15.23,18.85);stage('#close-stage',18.61,24);
tl.fromTo('#problem-text',{x:-35,opacity:0},{x:0,opacity:1,duration:.5,ease:'power3.out'},.12);
tl.fromTo('#status-signal',{y:25,opacity:0},{y:0,opacity:1,duration:.5,ease:'power2.out'},.25);
tl.fromTo('#outcome-signal',{x:45,opacity:0},{x:0,opacity:1,duration:.42,ease:'power3.out'},1.85);
tl.fromTo('#cause-head',{x:-35,opacity:0},{x:0,opacity:1,duration:.45,ease:'power2.out'},4.5);
tl.fromTo('#product-window',{x:65,y:20,scale:.98,opacity:0},{x:0,y:0,scale:1,opacity:1,duration:.62,ease:'power3.out'},4.55);
// Beat-grid accents: 6.00, 7.09, 8.19; labels hold together through 9.14.
tl.fromTo('#trace-logs',{x:-25,opacity:0},{x:0,opacity:1,duration:.32,ease:'power2.out'},5.97);
tl.fromTo('#trace-outcomes',{x:-25,opacity:0},{x:0,opacity:1,duration:.32,ease:'power2.out'},6.99);
tl.fromTo('#trace-change',{x:-25,opacity:0},{x:0,opacity:1,duration:.32,ease:'power2.out'},7.9);
tl.fromTo('.focus-bracket',{opacity:0},{opacity:1,duration:.25},6.8).to('.focus-bracket',{opacity:0,duration:.25},8.45);
tl.fromTo('#action-title',{y:24,opacity:0},{y:0,opacity:1,duration:.4,ease:'power2.out'},9.22);
tl.fromTo('#noise-card',{y:38,opacity:0},{y:0,opacity:1,duration:.45,ease:'power3.out'},9.4);
tl.fromTo('#fix-card',{y:38,opacity:0},{y:0,opacity:1,duration:.45,ease:'power3.out'},10.7);
// beat-locked: 13.11s, replay evidence aligns with narration's verification phrase.
tl.fromTo('#replay-card',{y:38,opacity:0},{y:0,opacity:1,duration:.45,ease:'power3.out'},13.11);
tl.fromTo('#decision-text',{x:-30,opacity:0},{x:0,opacity:1,duration:.4,ease:'power2.out'},15.27);
tl.fromTo('#decision-panel',{x:45,opacity:0},{x:0,opacity:1,duration:.43,ease:'power3.out'},15.3);
tl.fromTo('#decision-cursor',{x:110,y:70,opacity:0},{x:0,y:0,opacity:1,duration:.55,ease:'power2.out'},16.85);
// beat-locked: 17.47s, visible human approval interaction.
tl.fromTo('#press-ring',{scale:.3,opacity:.65},{scale:1.5,opacity:0,duration:.45,ease:'power2.out'},17.48);
tl.to('#approved-state',{opacity:1,duration:.18},17.55);tl.to('#review-state',{opacity:0,duration:.18},17.55);tl.to('#decision-cursor',{opacity:0,duration:.18},17.75);
tl.fromTo('#close-text',{y:28,opacity:0},{y:0,opacity:1,duration:.6,ease:'power3.out'},18.66);
tl.fromTo('.close-rule',{scaleX:0},{scaleX:1,duration:.72,ease:'power2.out'},19.5);
tl.fromTo('#close-product',{x:45,y:20,opacity:0},{x:0,y:0,opacity:1,duration:.65,ease:'power3.out'},20.05);
const labels=[[4.45,'02 / TRACE THE CAUSE',2],[9.14,'03 / DEFEND THE FIX',3],[15.23,'04 / HUMAN DECISION',4],[18.61,'05 / NEXUS LOOP',5]];
for(const [time,label,index] of labels){tl.set('#step-label',{textContent:label},time);tl.set('#bar'+index,{backgroundColor:'#2457C5'},time);}
tl.to('.backline',{x:45,duration:24,ease:'none'},0);tl.to('.canvas-dot',{y:25,duration:24,ease:'sine.inOut'},0);
// Pre-extracted music bands drive only the product-frame outline presence.
const data=window.NEXUS_AUDIO_DATA;if(data){for(let f=0;f<720&&f<data.frames.length;f++){const v=data.frames[f].bands[0];tl.set('#reactive-frame',{opacity:.12+v*.10},f/30);}}
window.__timelines['nexus-product']=tl;
'''
(comp / 'index.html').write_text('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=1920,height=1080"><title>Nexus Loop — Know what to change</title><script src="assets/vendor/gsap.min.js"></script><script src="assets/music/audio-data.js"></script><style>' + css + '</style></head><body><div id="root" data-composition-id="nexus-product" data-start="0" data-duration="24" data-width="1920" data-height="1080">' + body + '</div><script>' + script + '</script></body></html>')
motion = {'duration':24,'assertions':[{'kind':'appearsBy','selector':'#problem-text','bySec':0.8},{'kind':'before','a':'#status-signal','b':'#outcome-signal'}] + [{'kind':'staysInFrame','selector':'#'+s} for s in ['product-window','noise-card','fix-card','replay-card','decision-panel']]}
(comp / 'index.motion.json').write_text(json.dumps(motion))
(run / 'share-copy.txt').write_text('Nexus Loop connects agent logs to customer outcomes, identifies the change behind a regression, and puts evidence-backed improvement decisions in human hands.\n')
print('Built 24-second Nexus Loop composition with real product screens and voiced timeline.')
